odp:
  outputs:
    dev:
      type: clickhouse
      host: "{{ env_var('CLICKHOUSE_HOST', 'clickhouse') }}"
      port: "{{ env_var('CLICKHOUSE_PORT', '8123') | int }}"
      user: "{{ env_var('CLICKHOUSE_USER', 'default') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD', 'clickhouse_secret') }}"
      dbname: "{{ env_var('CLICKHOUSE_DB', 'odp') }}"
      schema: default
      secure: false
  target: dev
